





services:

  web:
    # image: wordpress:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        INSTALL_APPS: "${INSTALL_APPS}"
    networks:
    - wp_net
    container_name: wp_server
    ports:
    - 80:80
    depends_on:
      db: { condition: service_healthy  }
      cache: { condition: service_started }
    environment:
      WORDPRESS_DB_HOST: db_server
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}

  db:
    image: mariadb:latest
    container_name: db_server
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
    - wp_net
    restart: on-failure

  cache:
    image: redis:latest
    container_name: cache_server
    networks:
    - wp_net




volumes:
  db_data:  { name: db_data }

networks:
  wp_net:
    name: wp_net
    driver: bridge
