services:
  wp:
    image: wordpress:latest
    networks:
    - wp_net
    container_name: wp_server
    ports:
    - 80:80
    environment:
      WORDPRESS_DB_HOST: db_server
      WORDPRESS_DB_USER: app_user
      WORDPRESS_DB_PASSWORD: app_secure_pass
      WORDPRESS_DB_NAME: app_db

  db:
    image: mariadb
    container_name: db_server
    volumes:
    - db_data:/var/lib/mysql
    networks:
    - wp_net
    environment:
      MARIADB_ROOT_PASSWORD: my_secure_root_pass
      MARIADB_DATABASE: app_db
      MARIADB_USER: app_user
      MARIADB_PASSWORD: app_secure_pass


volumes:
  db_data:  { name: db_data }

networks:
  wp_net:
    name: wp_net
    driver: bridge
