services:
  wp:
    image: wordpress:latest
    networks:
    - wp_net
    container_name: wp_server
    ports:
    - 80:80
    environment:
      WORDPRESS_DB_HOST: db_server
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}

  db:
    image: mariadb
    container_name: db_server
    volumes:
    - db_data:/var/lib/mysql
    networks:
    - wp_net
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}

volumes:
  db_data:  { name: db_data }

networks:
  wp_net:
    name: wp_net
    driver: bridge
