Challenge Tasks
Task 1: Install & Verify
Check if Docker Compose is available on your machine
Verify the version
```bash
apt-get install docker-compose-plugin
docker compose version
docker version
```
---

